// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbsr_AptPOy4ozGeOGKxPzUTeYiehp0VQ',
    appId: '1:848049891560:web:3e792ddbead8517a2fc15d',
    messagingSenderId: '848049891560',
    projectId: 'iotreza-20664',
    authDomain: 'iotreza-20664.firebaseapp.com',
    databaseURL: 'https://iotreza-20664-default-rtdb.firebaseio.com',
    storageBucket: 'iotreza-20664.firebasestorage.app',
    measurementId: 'G-6ZBB4V5NKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDwpsWvRYLDT28AblzAx6saktGSxfL1gE',
    appId: '1:848049891560:android:b79ba4974324c2002fc15d',
    messagingSenderId: '848049891560',
    projectId: 'iotreza-20664',
    databaseURL: 'https://iotreza-20664-default-rtdb.firebaseio.com',
    storageBucket: 'iotreza-20664.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0TjYQoX-7YfFb6DFZvd7u5MUgUoGuBwc',
    appId: '1:848049891560:ios:6effec5549bb1ab52fc15d',
    messagingSenderId: '848049891560',
    projectId: 'iotreza-20664',
    databaseURL: 'https://iotreza-20664-default-rtdb.firebaseio.com',
    storageBucket: 'iotreza-20664.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0TjYQoX-7YfFb6DFZvd7u5MUgUoGuBwc',
    appId: '1:848049891560:ios:6effec5549bb1ab52fc15d',
    messagingSenderId: '848049891560',
    projectId: 'iotreza-20664',
    databaseURL: 'https://iotreza-20664-default-rtdb.firebaseio.com',
    storageBucket: 'iotreza-20664.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbsr_AptPOy4ozGeOGKxPzUTeYiehp0VQ',
    appId: '1:848049891560:web:bd48ba51a99423572fc15d',
    messagingSenderId: '848049891560',
    projectId: 'iotreza-20664',
    authDomain: 'iotreza-20664.firebaseapp.com',
    databaseURL: 'https://iotreza-20664-default-rtdb.firebaseio.com',
    storageBucket: 'iotreza-20664.firebasestorage.app',
    measurementId: 'G-8Y685RJXHJ',
  );
}
