// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQqfrmN0lzju2BY_M9ayVRIZejV4pl5Vc',
    appId: '1:388558775788:web:6285d79b826fdf50f30cc9',
    messagingSenderId: '388558775788',
    projectId: 'iotsmarthome-6da49',
    authDomain: 'iotsmarthome-6da49.firebaseapp.com',
    databaseURL: 'https://iotsmarthome-6da49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsmarthome-6da49.firebasestorage.app',
    measurementId: 'G-4DTBM74VWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXjy3-R9tjDaVQ6YrLH3okHBqdG1KEeeQ',
    appId: '1:388558775788:android:8552e77dcd04d256f30cc9',
    messagingSenderId: '388558775788',
    projectId: 'iotsmarthome-6da49',
    databaseURL: 'https://iotsmarthome-6da49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsmarthome-6da49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwooy2IomajwpMN0XnV4nPQ-oJdwczgcg',
    appId: '1:388558775788:ios:1814939c7646a81bf30cc9',
    messagingSenderId: '388558775788',
    projectId: 'iotsmarthome-6da49',
    databaseURL: 'https://iotsmarthome-6da49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsmarthome-6da49.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwooy2IomajwpMN0XnV4nPQ-oJdwczgcg',
    appId: '1:388558775788:ios:1814939c7646a81bf30cc9',
    messagingSenderId: '388558775788',
    projectId: 'iotsmarthome-6da49',
    databaseURL: 'https://iotsmarthome-6da49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsmarthome-6da49.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQqfrmN0lzju2BY_M9ayVRIZejV4pl5Vc',
    appId: '1:388558775788:web:3c6ffc1023886245f30cc9',
    messagingSenderId: '388558775788',
    projectId: 'iotsmarthome-6da49',
    authDomain: 'iotsmarthome-6da49.firebaseapp.com',
    databaseURL: 'https://iotsmarthome-6da49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsmarthome-6da49.firebasestorage.app',
    measurementId: 'G-9L2V2LKKNZ',
  );

}